gestion_etudiant_modules:
    path:     /{id}
    defaults: { _controller: GestionEtudiantBundle:Accueil:modules }

gestion_etudiant_accueil:
    path:     /
    defaults: { _controller: GestionEtudiantBundle:Accueil:index }

gestion_etudiant_homepage:
    path:     /etudiants/
    defaults: { _controller: GestionEtudiantBundle:Etudiant:index }

gestion_etudiant_fiche:
    path:     /etudiants/{id}
    defaults: { _controller: GestionEtudiantBundle:Etudiant:fiche }
gestion_etudiant_notes:
    path:     /{id_module}/notes
    defaults: { _controller: GestionEtudiantBundle:Notes:index}
gestion_etudiant_decision:
    path:     /decision/{annee}/{semestre}/{id_etudiant}
    defaults: { _controller: GestionEtudiantBundle:Decision:index}