<?php

namespace Proxies\__CG__\GestionEtudiantBundle\Entity;

/**
 * DO NOT EDIT THIS FILE - IT WAS CREATED BY DOCTRINE'S PROXY GENERATOR
 */
class Module extends \GestionEtudiantBundle\Entity\Module implements \Doctrine\ORM\Proxy\Proxy
{
    /**
     * @var \Closure the callback responsible for loading properties in the proxy object. This callback is called with
     *      three parameters, being respectively the proxy object to be initialized, the method that triggered the
     *      initialization process and an array of ordered parameters that were passed to that method.
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setInitializer
     */
    public $__initializer__;

    /**
     * @var \Closure the callback responsible of loading properties that need to be copied in the cloned object
     *
     * @see \Doctrine\Common\Persistence\Proxy::__setCloner
     */
    public $__cloner__;

    /**
     * @var boolean flag indicating if this object was already initialized
     *
     * @see \Doctrine\Common\Persistence\Proxy::__isInitialized
     */
    public $__isInitialized__ = false;

    /**
     * @var array properties to be lazy loaded, with keys being the property
     *            names and values being their default values
     *
     * @see \Doctrine\Common\Persistence\Proxy::__getLazyProperties
     */
    public static $lazyPropertiesDefaults = array();



    /**
     * @param \Closure $initializer
     * @param \Closure $cloner
     */
    public function __construct($initializer = null, $cloner = null)
    {

        $this->__initializer__ = $initializer;
        $this->__cloner__      = $cloner;
    }







    /**
     * 
     * @return array
     */
    public function __sleep()
    {
        if ($this->__isInitialized__) {
            return array('__isInitialized__', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'idUe', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'loginProf', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'nomModule', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'coefficient', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'id', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'notes');
        }

        return array('__isInitialized__', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'idUe', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'loginProf', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'nomModule', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'coefficient', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'id', '' . "\0" . 'GestionEtudiantBundle\\Entity\\Module' . "\0" . 'notes');
    }

    /**
     * 
     */
    public function __wakeup()
    {
        if ( ! $this->__isInitialized__) {
            $this->__initializer__ = function (Module $proxy) {
                $proxy->__setInitializer(null);
                $proxy->__setCloner(null);

                $existingProperties = get_object_vars($proxy);

                foreach ($proxy->__getLazyProperties() as $property => $defaultValue) {
                    if ( ! array_key_exists($property, $existingProperties)) {
                        $proxy->$property = $defaultValue;
                    }
                }
            };

        }
    }

    /**
     * 
     */
    public function __clone()
    {
        $this->__cloner__ && $this->__cloner__->__invoke($this, '__clone', array());
    }

    /**
     * Forces initialization of the proxy
     */
    public function __load()
    {
        $this->__initializer__ && $this->__initializer__->__invoke($this, '__load', array());
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitialized($initialized)
    {
        $this->__isInitialized__ = $initialized;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setInitializer(\Closure $initializer = null)
    {
        $this->__initializer__ = $initializer;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __getInitializer()
    {
        return $this->__initializer__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     */
    public function __setCloner(\Closure $cloner = null)
    {
        $this->__cloner__ = $cloner;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific cloning logic
     */
    public function __getCloner()
    {
        return $this->__cloner__;
    }

    /**
     * {@inheritDoc}
     * @internal generated method: use only when explicitly handling proxy specific loading logic
     * @static
     */
    public function __getLazyProperties()
    {
        return self::$lazyPropertiesDefaults;
    }

    
    /**
     * {@inheritDoc}
     */
    public function setIdUe($idUe)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setIdUe', array($idUe));

        return parent::setIdUe($idUe);
    }

    /**
     * {@inheritDoc}
     */
    public function getIdUe()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getIdUe', array());

        return parent::getIdUe();
    }

    /**
     * {@inheritDoc}
     */
    public function setLoginProf($loginProf)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setLoginProf', array($loginProf));

        return parent::setLoginProf($loginProf);
    }

    /**
     * {@inheritDoc}
     */
    public function getLoginProf()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getLoginProf', array());

        return parent::getLoginProf();
    }

    /**
     * {@inheritDoc}
     */
    public function setNomModule($nomModule)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNomModule', array($nomModule));

        return parent::setNomModule($nomModule);
    }

    /**
     * {@inheritDoc}
     */
    public function getNomModule()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNomModule', array());

        return parent::getNomModule();
    }

    /**
     * {@inheritDoc}
     */
    public function setCoefficient($coefficient)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setCoefficient', array($coefficient));

        return parent::setCoefficient($coefficient);
    }

    /**
     * {@inheritDoc}
     */
    public function getCoefficient()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getCoefficient', array());

        return parent::getCoefficient();
    }

    /**
     * {@inheritDoc}
     */
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return  parent::getId();
        }


        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getId', array());

        return parent::getId();
    }

    /**
     * {@inheritDoc}
     */
    public function getNotes()
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'getNotes', array());

        return parent::getNotes();
    }

    /**
     * {@inheritDoc}
     */
    public function setNotes($notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'setNotes', array($notes));

        return parent::setNotes($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function addNote(\GestionEtudiantBundle\Entity\Note $notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'addNote', array($notes));

        return parent::addNote($notes);
    }

    /**
     * {@inheritDoc}
     */
    public function removeNote(\GestionEtudiantBundle\Entity\Note $notes)
    {

        $this->__initializer__ && $this->__initializer__->__invoke($this, 'removeNote', array($notes));

        return parent::removeNote($notes);
    }

}
